<?php

declare(strict_types=1);

namespace EnvForm\Services;

use Illuminate\Support\Collection;
use Illuminate\Support\Facades\File;
use Symfony\Component\Finder\Finder;

/**
 * @phpstan-type EnvValue bool|int|string|null
 */
class DotEnvService
{
    /**
     * Find available .env files in the base path.
     *
     * @return array<string, string>
     */
    public function findFiles(string $basePath): array
    {
        $files = Finder::create()
            ->files()
            ->in($basePath)
            ->name('.env*')
            ->depth(0)
            ->ignoreDotFiles(false);

        $options = [];
        foreach ($files as $file) {
            $options[$file->getFilename()] = $file->getFilename();
        }

        return $options;
    }

    /**
     * Read and parse a .env file into a simple key-value collection.
     *
     * @return Collection<string, string>
     */
    public function read(string $path): Collection
    {
        if (! File::exists($path)) {
            return collect();
        }

        $content = File::get($path);
        $lines = explode("\n", $content);
        $values = collect();

        foreach ($lines as $line) {
            $line = trim($line);
            if (empty($line) || str_starts_with($line, '#')) {
                continue;
            }

            if (str_contains($line, '=')) {
                [$key, $value] = explode('=', $line, 2);
                $values->put(trim($key), trim($value, '"\' '));
            }
        }

        return $values;
    }

    /**
     * Update or create a .env file with given values and metadata.
     *
     * @param  array<string, EnvValue>  $values
     * @param  array<string, string>  $metadata  [ENV_KEY => GroupName]
     */
    public function write(string $path, array $values, array $metadata = []): void
    {
        $existing = $this->read($path)->toArray();
        $all = array_merge($existing, $values);

        $grouped = [];
        foreach ($all as $key => $value) {
            $group = $metadata[$key] ?? 'Other / Manually Added';
            $grouped[$group][$key] = $value;
        }

        ksort($grouped);

        $content = [
            '# Generated by Laravel EnvForm',
            '# Last updated: '.date('Y-m-d H:i:s'),
        ];

        foreach ($grouped as $groupName => $items) {
            $content[] = '';
            $content[] = "# --- {$groupName} ---";
            foreach ($items as $key => $value) {
                $content[] = "{$key}=".$this->formatValue($value);
            }
        }

        File::put($path, implode("\n", $content));
    }

    private function formatValue(mixed $value): string
    {
        if (\is_bool($value)) {
            return $value ? 'true' : 'false';
        }

        if (\is_null($value)) {
            return 'null';
        }

        $str = (string) $value;

        return preg_match('/\s|[#$]/', $str) ? "\"{$str}\"" : $str;
    }
}
