<?php

declare(strict_types=1);

namespace EnvForm\Services;

use Illuminate\Support\Facades\File;

/**
 * @phpstan-type EnvValue bool|int|string|null
 */
final class EnvWriter
{
    final public function __construct(
        protected string $path
    ) {}

    /**
     * @param  array<string, EnvValue>  $values
     * @param  array<string, string>  $metadata
     */
    final public function update(array $values, array $metadata = []): void
    {
        // 1. Get all current values from the file
        $existingValues = $this->parseExistingValues();

        // 2. Merge with updated values (updates override existing)
        $allValues = array_merge($existingValues, $values);

        // 3. Reorganize everything by group
        $grouped = [];
        foreach ($allValues as $key => $value) {
            $group = $metadata[$key] ?? 'Other / Manually Added';
            $grouped[$group][$key] = $value;
        }

        // 4. Sort groups to keep it consistent (Optional, but cleaner)
        ksort($grouped);

        // 5. Generate new content
        $newContent = [
            '# Generated by Laravel EnvForm',
            '# Last updated: '.date('Y-m-d H:i:s'),
        ];

        foreach ($grouped as $groupName => $items) {
            $newContent[] = '';
            $newContent[] = "# --- {$groupName} ---";

            foreach ($items as $key => $value) {
                $val = $this->formatValue($value);
                $newContent[] = "{$key}={$val}";
            }
        }

        File::put($this->path, implode("\n", $newContent));
    }

    /**
     * @return array<string, string>
     */
    private function parseExistingValues(): array
    {
        if (! File::exists($this->path)) {
            return [];
        }

        $content = File::get($this->path);
        $lines = explode("\n", $content);
        $values = [];

        foreach ($lines as $line) {
            $line = trim($line);
            if (empty($line) || str_starts_with($line, '#')) {
                continue;
            }

            if (str_contains($line, '=')) {
                [$key, $value] = explode('=', $line, 2);
                $values[trim($key)] = trim($value, '"\' ');
            }
        }

        return $values;
    }

    /**
     * @param  EnvValue  $value
     */
    private function formatValue($value): string
    {
        if (\is_bool($value)) {
            return $value ? 'true' : 'false';
        }

        if (\is_null($value)) {
            return 'null';
        }

        $stringVal = (string) $value;

        // Add quotes if value contains spaces or special characters
        if (preg_match('/\s|[#$]/', $stringVal)) {
            return '"'.$stringVal.'"';
        }

        return $stringVal;
    }
}
