<?php

declare(strict_types=1);

namespace EnvForm\DotEnv;

final readonly class Formatter
{
    /**
     * Format values into a .env string with grouping and comments.
     *
     * @param  array<string, bool|int|string|null>  $finalValues  [ENV_KEY => value]
     * @param  array<string, object{
     *  shouldAsk: bool,
     *  group: string
     * }>  $metadata  [ENV_KEY => {shouldAsk, group}]
     */
    final public function format(
        array $finalValues,
        array $metadata,
    ): string {
        $contentLines = [
            '# Generated by Laravel EnvForm',
            '# Last updated: '.date('Y-m-d H:i:s'),
        ];

        $grouped = [];

        foreach ($finalValues as $envKey => $value) {
            $grouped[$metadata[$envKey]->group][$envKey] = $value;
        }

        $grouped = collect($grouped)
            ->sortKeys()
            ->each(
                function (
                    array $items,
                    string $groupName
                ) use (&$contentLines, $metadata) {
                    $contentLines[] = '';
                    $contentLines[] = "# --- {$groupName} ---";

                    $items = collect($items)->sortBy(
                        fn (mixed $value, string $envKey) => ($metadata[$envKey]->shouldAsk ? 0 : 1).$envKey
                    );

                    foreach ($items as $envKey => $value) {
                        $line = "{$envKey}=".$this->formatValue($value);
                        $contentLines[] = $metadata[$envKey]->shouldAsk
                            ? $line
                            : "# {$line}";
                    }
                }
            );

        return implode("\n", $contentLines);
    }

    private function formatValue(mixed $value): string
    {
        if (\is_bool($value)) {
            return $value ? 'true' : 'false';
        }

        if (\is_null($value)) {
            return 'null';
        }

        if (\is_array($value)) {
            return 'null';
        }

        $str = (string) $value;

        return preg_match('/\s|[#$]/', $str) ? "\"{$str}\"" : $str;
    }
}
