<?php

declare(strict_types=1);

namespace EnvForm\DotEnv;

final class Formatter
{
    /**
     * Format values into a .env string with grouping and comments.
     *
     * @param  array<string, string|bool|int|null>  $activeValues
     * @param  array<string, string|bool|int|null>  $deprecatedValues
     * @param  array<string, string>  $metadata  [ENV_KEY => GroupName]
     */
    public function format(array $activeValues, array $deprecatedValues, array $metadata): string
    {
        $grouped = [];

        // Group Active Keys by their configuration file name
        foreach ($activeValues as $key => $value) {
            $group = $metadata[$key] ?? 'Other / Manually Added';
            $grouped[$group][$key] = $value;
        }

        // Group Deprecated Keys
        if (! empty($deprecatedValues)) {
            foreach ($deprecatedValues as $key => $value) {
                $grouped['ZZZ_Deprecated'][$key] = $value;
            }
        }

        ksort($grouped);

        $content = [
            '# Generated by Laravel EnvForm',
            '# Last updated: '.date('Y-m-d H:i:s'),
        ];

        foreach ($grouped as $groupName => $items) {
            $isDeprecated = ($groupName === 'ZZZ_Deprecated');
            $displayName = $isDeprecated ? 'Deprecated / Unused' : $groupName;

            $content[] = '';
            $content[] = "# --- {$displayName} ---";

            foreach ($items as $key => $value) {
                $line = "{$key}=".$this->formatValue($value);
                $content[] = $isDeprecated ? "# {$line}" : $line;
            }
        }

        return implode("\n", $content);
    }

    private function formatValue(mixed $value): string
    {
        if (\is_bool($value)) {
            return $value ? 'true' : 'false';
        }

        if (\is_null($value)) {
            return 'null';
        }

        if (\is_array($value)) {
            return 'null';
        }

        $str = (string) $value;

        return preg_match('/\s|[#$]/', $str) ? "\"{$str}\"" : $str;
    }
}
